### ISSUE TITLE
Ruby >= 2.0.0 requirement

### ISSUE THREAD

**Issue by gemp** [grosser/sort_alphabetical#21]
Apparently v1.1.0 produce the following error under Ruby 1.9.3, tho the readme indicates "Ruby >= 1.9" requirement:
```
ERROR:  Error installing sort_alphabetical:
	sort_alphabetical requires Ruby version >= 2.0.0.
```
"~> 1.0.0" agreed to install v1.0.2.

**Comment by grosser** [comment]
thx, removed that :)
