### ISSUE TITLE
Wrong order with 'Ñ' character

### ISSUE THREAD

**Issue by jorgevbo** [grosser/sort_alphabetical#22]
I've a array with values:
array = ['QUIÑO', 'QUINT']

When I use:
array.sort_alphabetical

Expectected result will be:
["QUINT", "QUIÑO"]

However, I got:
["QUIÑO", "QUINT"]

**Comment by grosser** [comment]
caused by https://github.com/grosser/sort_alphabetical/issues/20 I'd say ...
this is just a thin wrapper so not really able to fix basic issues like that ... try https://github.com/fantasticfears/ffi-icu
